services:
  - type: web
    name: transporte-escolar-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: https://tu-backend.onrender.com
